---
title: "First project"
output: html_document
date: "2023-01-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(dplyr)
library(stringr)
```

```{r}
covid_data <- read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv")
#summary (covid_data)
```

```{r, eval=FALSE}
#unique(covid_data$location)
#unique(covid_data$continent)

empty_covid <- covid_data %>% filter(is.na(continent))
empty_covid 

unique(covid_data$continent)
empty_covid2 <- covid_data %>% filter(continent == "" | location == "Africa")
empty_covid2

empty_covid_l <- covid_data %>% filter(location == "Africa")
empty_covid_l

empty_covid_lw <- covid_data %>% filter(location == "World")
empty_covid_lw

empty_covid_c <- covid_data %>% filter(continent == "Africa")
empty_covid_c

```

```{r,}
oc_data <- covid_data %>% 
  select('continent', 'location', 'date', 'hosp_patients', 'extreme_poverty','new_deaths', 'total_deaths') %>%
  filter(location == "Oceania"|continent == "Oceania") %>%
  mutate(location = replace(location,location == "Oceania", "Australia"))

oc_data$continent %>% replace_na('Oceania' )

#head(oc_data)
#tail(oc_data)
```
```{r}
oc_start <- oc_data[oc_data$date >= "2020-03-01" & oc_data$date <= "2022-12-31", ]

oc_start$hosp_patients[is.na(oc_start$hosp_patients)] <- 0
oc_start$new_deaths[is.na(oc_start$new_deaths)] <- 0

oc_start
```
```{r}
library(ggplot2)


```

